from .nodes import (
    DashScopeAudioUpload,
    DashScopeCosyVoiceTTS,
    DashScopeFileUpload,
    DashScopeHappyHorseImageToVideo,
    DashScopeHappyHorseReferenceToVideo,
    DashScopeHappyHorseTextToVideo,
    DashScopeHappyHorseVideoEdit,
    DashScopeMiniMaxSpeech,
    DashScopeMiniMaxVoiceClone,
    DashScopeQwenOmniImage,
    DashScopeQwenOmniVideo,
    DashScopeQwenTTS,
    DashScopeTextToImage,
    DashScopeTextToImageAsync,
)

NODE_CLASS_MAPPINGS = {
    "DashScopeFileUpload": DashScopeFileUpload,
    "DashScopeAudioUpload": DashScopeAudioUpload,
    "DashScopeTextToImage": DashScopeTextToImage,
    "DashScopeTextToImageAsync": DashScopeTextToImageAsync,
    "DashScopeHappyHorseTextToVideo": DashScopeHappyHorseTextToVideo,
    "DashScopeHappyHorseImageToVideo": DashScopeHappyHorseImageToVideo,
    "DashScopeHappyHorseReferenceToVideo": DashScopeHappyHorseReferenceToVideo,
    "DashScopeHappyHorseVideoEdit": DashScopeHappyHorseVideoEdit,
    "DashScopeQwenOmniVideo": DashScopeQwenOmniVideo,
    "DashScopeQwenOmniImage": DashScopeQwenOmniImage,
    "DashScopeQwenTTS": DashScopeQwenTTS,
    "DashScopeMiniMaxSpeech": DashScopeMiniMaxSpeech,
    "DashScopeMiniMaxVoiceClone": DashScopeMiniMaxVoiceClone,
    "DashScopeCosyVoiceTTS": DashScopeCosyVoiceTTS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "DashScopeFileUpload": "DashScope File Upload (to OSS)",
    "DashScopeAudioUpload": "DashScope Audio Upload (to OSS)",
    "DashScopeTextToImage": "DashScope Text to Image",
    "DashScopeTextToImageAsync": "DashScope Text to Image (Async)",
    "DashScopeHappyHorseTextToVideo": "DashScope HappyHorse Text to Video",
    "DashScopeHappyHorseImageToVideo": "DashScope HappyHorse Image to Video (First Frame)",
    "DashScopeHappyHorseReferenceToVideo": "DashScope HappyHorse Reference to Video",
    "DashScopeHappyHorseVideoEdit": "DashScope HappyHorse Video Edit",
    "DashScopeQwenOmniVideo": "DashScope Qwen Omni - Video Understanding",
    "DashScopeQwenOmniImage": "DashScope Qwen Omni - Image Understanding",
    "DashScopeQwenTTS": "DashScope Qwen TTS",
    "DashScopeMiniMaxSpeech": "DashScope MiniMax Speech Synthesis",
    "DashScopeMiniMaxVoiceClone": "DashScope MiniMax Voice Clone",
    "DashScopeCosyVoiceTTS": "DashScope CosyVoice TTS",
}
